name = "Winter's Summer"
author = "asojidev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b455d61752f62abac3d81b134f416e3cb720b25618baa9fcc347a2fa34e02b0a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
