name = "Winter's Summer"
author = "asojidev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "630cd778be02ed9ba6641fe2fc860db69321934eb39ae1ee111dfc19eb4cf0e1"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
